id = "pkl-icons"
name = "Pkl Icons"
description = "Material Icon Theme file and folder icons for Zed, with the official Pkl logo for Pkl files."
version = "0.2.0"
schema_version = 1
authors = ["Eduardo Aguilar <eduardo.aguilar@draftea.com>"]
repository = "https://github.com/danteay/pkl-zed-icons"
